###############################################
# This file is generated by @xml-ormz.
# You can modify it when your project needs.
###############################################

from xo.orm import Model, Optional, StringField, FloatField, IntegerField, ForeignKeyField 


class HostedFunction(Model):
    Guid = StringField()
    GuidDef = StringField()
    Hardware = StringField()
    Name = StringField()
    NameDef = StringField()
    XsdVersion = FloatField()
    
        
    class A429Port(Model):
        Guid = StringField()
        GuidDef = StringField()
        Name = StringField()
        NameDef = StringField()
        Physical = StringField()
        
            
        class A429Channel(Model):
            Guid = StringField()
            GuidDef = StringField()
            Name = StringField()
            NameDef = StringField()
            
                
            class A429Word(Model):
                Guid = StringField()
                GuidDef = StringField()
                Name = StringField()
                NameDef = StringField()
                
                    
                class DP(Model):
                    CodedSet = Optional( StringField() )
                    Guid = StringField()
                    GuidDef = StringField()
                    Name = StringField()
                    NameDef = StringField()
                    
                
            
        class Dataflow_Ref(Model):
            SrcGuid = StringField()
            SrcName = StringField()
            
        class RP(Model):
            Guid = StringField()
            GuidDef = StringField()
            Name = StringField()
            NameDef = StringField()
            
                
            class Pub_Ref(Model):
                SrcGuid = StringField()
                SrcName = StringField()
                
            
        
    